using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PauseMenu : MonoBehaviour
{
    public static bool GameIsPaused = false;

    public GameObject pauseMenuUI;
    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown("space"))
        {
            if (GameIsPaused)
            {
                Resume();
            }
            else
            {
                Pause();
            }
        }
    }

    public void Resume()
    {
        pauseMenuUI.SetActive(false);
        Time.timeScale = 1.0f;
        Time.fixedDeltaTime = 1.0f;
        GameIsPaused = false;
    }

    void Pause()
    {
        pauseMenuUI.SetActive(true);
        Time.timeScale = 0.0f;
        Time.fixedDeltaTime = 0.0f;
        GameIsPaused = true;
    }

    public void mainMenu()
    {
        SceneManager.LoadScene(0);
        GameIsPaused = false;
        Time.timeScale = 1.0f;
        Time.fixedDeltaTime = 1.0f;
    }

    public void quitGame()
    {
        Application.Quit();
    }
}
